<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="CHMB106376" failures="1" tests="2" name="Surefire test" time="0.031" errors="0" timestamp="14 Jun 2023 19:25:51 GMT">
  <testcase classname="MyFirstClassTest" name="canAddTwoPlusTwo" time="0.008"/>
  <testcase classname="Testing1" name="canAddTwoPlusTwo" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [6] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [4]
at Testing1.canAddTwoPlusTwo(Testing1.java:9)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- canAddTwoPlusTwo -->
</testsuite> <!-- Surefire test -->
